development:
  encoding: UTF-8
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: heroku_development
  timeout: 5000
  password: 111111

test:
  encoding: UTF-8
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: heroku_test
  timeout: 5000
  password: 111111

production:
  encoding: UTF-8
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: heroku_production
  timeout: 5000
  password: 111111 